import 'package:flutter/material.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedBUYTICKETWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedChristopherNolansInterstellaraboutastronautstravelingto.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/Generated20192hr35minSciFciWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedINTERSTELLARWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget1/generated/GeneratedRectangle6Widget1.dart';

/* Frame Google Pixel 2 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel21Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 722.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 67.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 423.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 22.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 96.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 48.0,
                child: GeneratedINTERSTELLARWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 102.0,
                child:
                    GeneratedChristopherNolansInterstellaraboutastronautstravelingto(),
              ),
              Positioned(
                left: 119.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 23.0,
                child: Generated20192hr35minSciFciWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.22222137451172,
                height: 17.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 99.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 46.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 136.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 37.0,
                child: GeneratedBUYTICKETWidget(),
              )
            ]),
      ),
    ));
  }
}
