import 'package:flutter/material.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedAvengersEndgameWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedMenu1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedTrailersWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedNotification11Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedViewallWidget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedLostinspace1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedComingSoonWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedSearch1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedProfileuser1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedNowinCinemasWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedViewallWidget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedPassenger1Widget.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel21widget/generated/GeneratedGroup9Widget.dart';

/* Frame Google Pixel 2 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 233.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedSearch1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedMenu1Widget(),
              ),
              Positioned(
                left: 283.4148864746094,
                top: 84.98577880859375,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedNotification11Widget(),
              ),
              Positioned(
                left: 359.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedProfileuser1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 30.0,
                child: GeneratedTrailersWidget(),
              ),
              Positioned(
                left: 350.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedAvengersEndgameWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 27.0,
                child: GeneratedNowinCinemasWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 27.0,
                child: GeneratedComingSoonWidget(),
              ),
              Positioned(
                left: 326.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 27.0,
                child: GeneratedViewallWidget(),
              ),
              Positioned(
                left: 329.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 27.0,
                child: GeneratedViewallWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 31.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 354.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 9.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 31.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 187.0,
                child: GeneratedPassenger1Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 182.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 350.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 186.0,
                child: GeneratedLostinspace1Widget(),
              ),
              Positioned(
                left: 356.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 356.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: -927.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 703.0,
                height: 798.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 182.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle7Widget(),
              )
            ]),
      ),
    ));
  }
}
