import 'package:flutter/material.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedComingSoonWidget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedAvengersEndgameWidget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedProfileuser1Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedViewallWidget2.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedViewallWidget3.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedNotification11Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedMenu1Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedSearch1Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedTrailersWidget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedNowinCinemasWidget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedPassenger1Widget1.dart';
import 'package:flutterapp/app_inventivapp/generatedgooglepixel22widget/generated/GeneratedGroup8Widget1.dart';

/* Frame Google Pixel 2 - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 233.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedSearch1Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedMenu1Widget1(),
              ),
              Positioned(
                left: 283.4148864746094,
                top: 84.98577880859375,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedNotification11Widget1(),
              ),
              Positioned(
                left: 359.0,
                top: 71.80068969726562,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedProfileuser1Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 30.0,
                child: GeneratedTrailersWidget1(),
              ),
              Positioned(
                left: 350.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 27.0,
                child: GeneratedAvengersEndgameWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 27.0,
                child: GeneratedNowinCinemasWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 27.0,
                child: GeneratedComingSoonWidget1(),
              ),
              Positioned(
                left: 326.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 27.0,
                child: GeneratedViewallWidget2(),
              ),
              Positioned(
                left: 329.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 27.0,
                child: GeneratedViewallWidget3(),
              ),
              Positioned(
                left: 36.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 31.0,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 354.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 9.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 196.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 31.0,
                child: GeneratedGroup9Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 187.0,
                child: GeneratedPassenger1Widget1(),
              ),
              Positioned(
                left: 166.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedGroup6Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 212.0,
                child: GeneratedRectangle4Widget1(),
              )
            ]),
      ),
    ));
  }
}
